defb "Barbarian    I"
defb "Barbarian   II"
defb "Boulder Dash  "
defb "Boulder Dash 3"
defb "Bomb Jack     "
defb "Bruce Lee     "
defb "Cauldron     I"
defb "Cauldron    II"
defb "Commando      "
defb "Cynernoid    I"
defb "Cynernoid   II"
defb "Dan Dare     I"
defb "Dan Dare   III"
defb "Dark Fusion   "
defb "Death Star    "
defb "Eagle's Nest  "
defb "Earth Shaker  "
defb "Exolon        "
defb "Freddy Hardest"
defb "Fr. Hardest II"
defb "Ikari         "
defb "Jack Nipper   "
defb "Kwik Snax     "
defb "Lode Runner  I"
defb "Lode Runner  2"
defb "Manic Miner  I"
defb "Manic Miner  2"
defb "Nether Earth  "
defb "Panama Joe    "
defb "Sigma Seven   "
defb "Solomon's Key "
defb "Starquake     "
defb "The cyclone   "
defb "Treasure Isle "
defb "Venom Mask III"
defb "Zybex         "



